### ISSUE TITLE
Will Django/Broomhilda support btn in the future?

### ISSUE THREAD

**Issue by DaMauu** [jimpalompa/ptp#3]
I like this stylesheet so much that I even want to apply it to multiple popular sites!

**Comment by jimpalompa** [comment]
Thank you very much! I would like to also, but btn has a completely different source to style.

I actually just made this stylesheet for me to use, but decided to share it for other users as well. I'm glad people liked it.

Too much work for me to make a new one, so the answer is no. Now eat your popcorn! 🍿
